spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

server:
  port: 24455

eureka:
  enableSelfPreservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: ${eureka.enableSelfPreservation}
